---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: heading
    label: Content
  - type: directory
    path: content/locations
    label: Locations
    create: documents
    match: "**/*"
  - type: directory
    path: content/posts
    label: Blog Posts
    create: documents
    match: "**/*"
  - type: document
    path: content/about.md
    label: About Us
    match: "**/*"
  - type: heading
    label: Config
  - type: document
    path: config.json
    label: Site Info
    match: "**/*"
    read_only: false
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
